PalLocalPlanner:
  transform_tolerance: 0.2

  acc_lim_x    : 0.8
  acc_lim_theta: !degrees 96.0

  max_vel_x : &max_vel_x 0.3
  max_vel_th: !degrees 36.0

  xy_goal_tolerance : 0.2
  yaw_goal_tolerance: !degrees 12.0

  oscillation_reset_dist: 0.1

  travel_speed_sfl   : *max_vel_x
  point_b_sfl        : 0.26
  decay              : 0.85
  max_dist_plan_ahead: 4.0
  dist_to_avoid      : 0.25
  allow_backwards    : false

  obstacle_avoider: 0 # VFH
  robotWidth      : 0.5
  robotLength     : 0.5
  robotFrontLength: 0.25
  safetyDist      : 2.2
  use_crowd       : false

  bumpers: false
