recovery_behaviors:
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate'
    type: rotate_recovery/RotateRecovery

aggressive_reset:
  reset_distance: 1.5
  layer_names: ["obstacle_laser_layer", "obstacle_rgbd_layer"]

rotate:
  max_rotational_vel: 0.6
