recovery_behaviors:
  - name: 'refresh_vo'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate'
    type: rotate_recovery/RotateRecovery
  - name: 'dummy'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

aggressive_reset:
  reset_distance: 1.5
  layer_names: ["obstacle_laser_layer", "obstacle_rgbd_layer"]

rotate:
  max_rotational_vel: 0.6

refresh_vo:
  reset_distance: 0.0
  layer_names: ["obstacle_vo_layer"]

dummy:
  reset_distance: 5.5
  layer_names: ["obstacle_laser_layer", "obstacle_rgbd_layer", "obstacle_vo_layer"]