camera_link: base_rgbd_camera_optical_frame

confidence_threshold: 200

# Downsampling (using PCL voxel grid filter)
use_voxel_grid_filter: true
voxel_grid_side      : 0.03

# Outlier removal (using PCL radius outlier removal filter)
# Note that this is applied on the output of the downsampling filter!
use_radius_filter: true
search_radius    : 0.05
min_neighbours   : 20

# PassThrough filter
use_passthrough_filter: true
limit_min             :  0.1
limit_max             : 10.0

# Frustum Culling filter
use_frustum_culling_filter: true
hfov                      :  40.0
vfov                      :  60.0
near_plane                :   0.0
far_plane                 : 100.0

enable_depth      : true
depth_mode        : long   # close, long
depth_frame_format: QQVGA  # QQVGA, QVGA, VGA
depth_frame_rate  : 30     # 25, 30, 50, 60

# @todo with the current driver we cannot use depth and color simultaneously
enable_color      : false
color_compression : YUY2   # YUY2, MJPEG
color_frame_format: VGA    # QQVGA, QVGA, VGA, NHD, WXGA_H
color_frame_rate  : 30     # 30

range_max: 4.0 # m
