driver:
    # Modes:
    #  1 :  SXGA @ 30Hz
    #  2 :  SXGA @ 15Hz
    #  3 :   XGA @ 30Hz
    #  5 :   XGA @ 15Hz
    #  6 :   VGA @ 30Hz
    #  7 :   VGA @ 25Hz
    #  8 :  QVGA @ 25Hz
    #  9 :  QVGA @ 30Hz
    # 10 : QQVGA @ 25Hz
    # where (http://en.wikipedia.org/wiki/Graphics_display_resolution):
    #  SXGA = 1280x1024
    #   XGA = 1024x768
    #   VGA =  640x480
    #  QVGA =  320x240
    # QQVGA =  160x120
    #
    # Only mode #8 is supported.
    ir_mode   : 8
    color_mode: 8
    depth_mode: 8

    # Skip #frames, so the frame rate turns into:
    # frame_rate /= (1 + data_skip)
    # which for mode #8 (30Hz) and data_skip = 4 gives:
    # 30Hz / (1 + 4) = 30Hz / 5 = 6Hz
    data_skip : 4

depth_points:
    range_max: &depth_range_max 10.0

points_xyzrgb_hw_registered:
    range_max: *depth_range_max
