slam_karto:
  base_frame: base_footprint

  # Scans:
  minimum_travel_distance: 0.2
  minimum_travel_heading : !degrees 10
  range_threshold        : 9.5  # laser max range: 10
  use_scan_barycenter    : true
  resolution             : 0.025

  # ! As for now this feature works only with SICK lasers
  map_free_space         : false
