min_height: 0.05
max_height: 2.0

angle_min      : !degrees -14.0 #-25.0
angle_max      : !degrees  14.0 #25.0
angle_increment: !degrees   0.1
scan_time: 0.166 # 6Hz (0.033 -> 30Hz)

# Range [min, max] greater than the actual sensor
# e.g. Xtion Pro Live is [0.8, 3.5]m
range_min:  2.1  # m
range_max: 5.3   # m

target_frame: rgbd_laser_link

use_concurrency: false
use_inf        : true